swagger: '2.0'
info:
  description: Weather requests api
  version: 1.0.0 #API version
  title: Weather requests # API title
  license: #Swagger license info
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: localhost
schemes:
  - http
tags:
  - name: Weather
paths:
  '/getDailyWeatherInfo':
    get:
      tags:
        - Weather
      summary: get daily weather info by city, from startDate to endDate
      description: Returns daily weather info (min temp, max temp, avg temp)
      operationId: getDailyWeatherInfo
      produces:
        - application/json
      parameters:
        - name: city
          in: query
          description: name of city from which you want to get weather info
          required: true
          type: string
        - name: startDate
          in: query
          description: date from which you want to get weather info
          required: true
          type: string
        - name: endDate
          in: query
          description: date to with you want to get weather info
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/WeatherDailyData' #Response object details
        '400':
          description: Invalid parameters
        '404':
          description: Weather info not found

  '/getSeasonWeatherInfo':
    get:
      tags:
        - Weather
      summary: get season weather info by city, from startDate to endDate
      description: Returns season weather info (min temp, max temp, avg temp)
      operationId: getSeasonWeatherInfo
      produces:
        - application/json
      parameters:
        - name: city
          in: query
          description: name of city from which you want to get weather info
          required: true
          type: string
        - name: startDate
          in: query
          description: date from which you want to get weather info
          required: true
          type: string
        - name: endDate
          in: query
          description: date to with you want to get weather info
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/WeatherSeasonData' #Response object details
        '400':
          description: Invalid parameters
        '404':
          description: Weather info not found
definitions:
  WeatherDailyData:
    type: object
    properties:
      data:
        type: array
        items:
          $ref: 'TemperatureDailyInfo'
        description: list of temp daily infos
  TemperatureDailyInfo:
    type: object
    properties:
      date:
        type: string
        description: date of temp
      tavg:
        type: string
        description: avg temp in this date
      tmin:
        type: string
        description: min temp in this date
      tmax:
        type: string
        description: max temp in this date
  WeatherRequest:
    type: object
    properties:
      city:
        type: string
      startDate:
        type: string
      endDate:
        type: string
  TemperatureInfoBySeason:
    type: object
    properties:
      season:
        type: string
      year:
        type: string
      maxTemp:
        type: string
      minTemp:
        type: string
      avgTemp:
        type: string
  WeatherSeasonData:
    type: object
    properties:
      data:
        type: array
        items:
          $ref: 'TemperatureInfoBySeason'

