swagger: '2.0'
info:
  description: News requests api
  version: 1.0.0 #API version
  title: News requests # API title
  license: #Swagger license info
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: localhost
schemes:
  - http
paths:
  '/v2/everything':
    get:
      tags:
        - News
      summary: get news by q
      description: returns news by special word
      operationId: getNewsData
      produces:
        - application/json
      parameters:
        - name: q
          in: query
          description: Keywords or phrases to search for in the article title and body
          required: true
          type: string
        - name: pageSize
          in: query
          description: The number of results to return per page
          required: false
          type: integer
        - name: page
          in: query
          description: Use this to page through the results.
          required: false
          type: integer
        - name: apiKey
          in: query
          description: Your API key
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/NewsData' #Response object details
        '400': #Unsuccessful response code
          description: Invalid request #Unsuccessful response description
        '404': #Unsuccessful response code
          description: Address not found #Unsuccessful response description
definitions:
  NewsData:
    type: object
    properties:
      totalResults:
        type: integer
        description: The total number of results available for your request
      articles:
        type: array
        items:
          $ref: 'Article'
        description: articles info
  Article:
    type: object
    properties:
      author:
        type: string
        description: article author
      title:
        type: string
        description: article title
      description:
        type: string
        description: article description
      url:
        type: string
        description: article url
      urlToImage:
        type: string
        description: article url to image
      publishedAt:
        type: string
        description: article published date
      content:
        type: string
        description: article content
      source:
        type: object
        $ref: 'Source'
  Source:
    type: object
    properties:
      id:
        type: string
        description: article source id
      name:
        type: string
        description: article source name
  NewsRequest:
    type: object
    properties:
      q:
        type: string
      page:
        type: integer
      pageSize:
        type: integer


